name: GA Demo Workflow

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.12'

            - name: Install Dependencies
              run: |
                python3 -m pip install --upgrade pip
                pip install --no-cache-dir -r requirements.txt
            
            - name: Build Docker Image
              run: |
                docker build -t ${{ vars.DOCKER_USERNAME }}/ga-demo-app:${{ github.sha }} .

            - name: Scan container image for vulnerabilities
              uses: aquasecurity/trivy-action@0.28.0
              with:
                image-ref: 'docker.io/fykio/ga-demo-app:${{ github.sha }}'
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL,HIGH'

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PAT_TOKEN }}

            - name: Push Docker Image
              run: |
                docker push ${{ vars.DOCKER_USERNAME }}/ga-demo-app:${{ github.sha }}
